# Generated by Django 2.1.7 on 2019-03-04 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='owner',
        ),
    ]
